server:
  port: 8081
spring:
  application:
    name: wisetour
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wisetour?useSSL=false&serverTimezone=UTC
    username: root
    password: iicebear1104
  redis:
    host: 172.27.170.110
    port: 6379
    password: 71704
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq: #test
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true           # 开启消费者自动重试
          max-attempts: 3         # 最大重试3次（1次正常消费+2次重试）
          initial-interval: 1000ms # 重试间隔
          multiplier: 2.0         # 间隔倍数(1s, 2s)
        default-requeue-rejected: false # 重试耗尽后拒绝消息，直接投递到死信队列
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.wisetour.entity # 别名扫描包
logging:
  level:
    com.wisetour: debug